#!/usr/bin/env bash

set -e

DB_NAME=$(php <<< '<?php require "config.php"; echo DB_NAME;')

function finish {
    dropdb --if-exists $DB_NAME
    [ $PHP_PID ] && kill $PHP_PID
}
trap finish EXIT

echo ''
echo '==============='
echo 'Create database'
echo '==============='
echo ''

dropdb --if-exists $DB_NAME
createdb $DB_NAME

vendor/bin/phinx migrate

echo ''
echo '=============='
echo 'Run web server'
echo '=============='
echo ''

cd public
php -S localhost:9000 index.php &
PHP_PID=$!
cd ..

echo ''
echo '========='
echo 'Run tests'
echo '========='
echo ''

vendor/bin/behat --colors
